### ISSUE TITLE
babel-register error

### ISSUE THREAD

**Issue by duryjames** [contentful/contentful-space-sync#48]
Hi,

I have installed this package like below

```
npm install -g contentful-space-sync
```

But i am getting this issue when i run it:

```

$ contentful-space-sync --config contentful-sync.json
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-space-sync/index.js:5:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-space-sync/bin/space-sync:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

If i install babel-register

```
npm install -g babel-register
```

Then i get the following error:

```

$ contentful-space-sync --config contentful-sync.json
module.js:338
    throw err;
    ^
Error: Cannot find module './lib/run-space-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-space-sync/index.js:6:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-space-sync/bin/space-sync:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

My "contentful-sync.json" json looks like the following:

```
{
  "sourceSpace": "u49qxxxxxxx",
  "destinationSpace": "8rg2xxxxxxx",
  "sourceDeliveryToken": "20af64fc6aa0ffxxxxxxxxx",
  "managementToken": "b73b7b968a6bf0xxxxxxxxx"
}
```

**Comment by trodrigues** [comment]
Hi there,

apologies for the issue. This somehow didn't reveal itself on a local installation but it's a problem in the built and published version of the package.

For now I suggest you use 2.1.9 with `npm i -g contentful-space-sync@2.1.9`

**Comment by duryjames** [comment]
Brilliant thanks a lot, its all working now

**Comment by trodrigues** [comment]
I just published version 3.0.1 which fixes the issue you initially reported. If you'd like to give that a try and report back I'd appreciate it.

**Comment by Flood** [comment]
I have the same problem for "contentful": "3.7.1", it complains about babel-register. When I install that it throws on:

Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/contentful/lib/contentful.js

And there is no lib folder.

**Comment by Khaledgarbaya** [comment]
@Flood , is this related to space-sync-tool ?
If not, please create an issue in the contentful.js repo

**Comment by Flood** [comment]
No, it's for contentful.js. Thanks anyway
