### ISSUE TITLE
TypeError: Cannot read property 'publish' of undefined

### ISSUE THREAD

**Issue by nikolaiwu** [contentful/contentful-space-sync#90]
It's been a while, since last synchronization of our QA space, so we decided to update it from Production space, to get a fresh copy. I've cleared all content of the QA space (entries, assets and content types) and then I started the tool. It created all content types, then it started on the assets, where it blew up with an error. Here's the log:

```
...
info Processing Asset 3P1SgZy7oIIyEukswOwc6i
ERR! Failed with
 TypeError: Cannot read property 'publish' of undefined
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/push/publishing.js:34:18
ERR! Failed with
     at tryCatcher (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/util.js:16:23)
ERR! Failed with
     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/map.js:57:38)
ERR! Failed with
     at MappingPromiseArray.PromiseArray._iterate (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise_array.js:113:31)
ERR! Failed with
     at MappingPromiseArray.init (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise_array.js:77:10)
ERR! Failed with
     at new MappingPromiseArray (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/map.js:25:10)
ERR! Failed with
     at map (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/map.js:152:12)
ERR! Failed with
     at Function.Promise.map (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/map.js:160:12)
ERR! Failed with
     at Object.publishEntities (/usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/push/publishing.js:33:29)
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/push/push-to-space.js:81:84
ERR! Failed with
     at tryCatcher (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/util.js:16:23)
ERR! Failed with
     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:504:31)
ERR! Failed with
     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:561:18)
ERR! Failed with
     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:606:10)
ERR! Failed with
     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:685:18)
ERR! Failed with
     at Promise._fulfill (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:630:18)
ERR! Failed with
  [TypeError: Cannot read property 'publish' of undefined]
```

The script manage to copy most of the assets (793 of 832). I've checked the last printed asset (the one with id "3P1SgZy7oIIyEukswOwc6i"), everything is looking fine there, I assume that the next asset in the line is the problematic one.

So, here is my questions:
1. How can I track down the "broken" asset?
2. What could be wrong with that asset? `Cannot read property 'publish' of undefined` tells me that either it doesn't get the asset object, or something is wrong with it's structure of the object.
3. Is there any anti-patterns we should avoid (except links to drafts) with the structure of the content?
4. I've asked before, but you guys are being busy and upgrading a lot of your services, so is this tool still the best choice for us to have 2 separate environments and keep them synced?
5. Just a thought, is it possible for us not to have QA space at all, instead to use the "Roles and permissions" functionality to test and develop new features on the QA site, without showing them on production, and publish them after? If so, please send me some resources on the subject.

Any help will be greatly appreciated! Thank you!

**Comment by Khaledgarbaya** [comment]
Hi @nikolaiwu ,
This could be due to an entry that previously failed publishing for some reason like a broken link 
for example.
I totally agree with you that you should use roles and permission for your workflow.
You can find more info about it here: https://www.contentful.com/r/knowledgebase/roles-and-permissions/

To be able to help you more about the checking what actually happened with asset I would suggest that you create a ticket at support.contentful.com from I will be able to check what is wrong with the data.

Best,

Khaled

**Comment by nikolaiwu** [comment]
Thank you @Khaledgarbaya,
the issue is submitted! 

Regarding roles and permissions, I've read that article, also the related FAQ, but I need something a bit more technical. Like for example, how to configure the production website to get the content from the client and not our dev testing versions, and the QA site to get all content from the client plus our dev testing data. I didn't find any information about that. Should I submit another ticket to the support, since this thread is not entirely relevant to that issue?

Feel free to close this issue and move this conversation to the support website.

Thank you for your help!

Best Regards,
Nikolai

**Comment by Khaledgarbaya** [comment]
Yeah let's move to the ticket
